# Generated by Django 5.1.3 on 2024-11-17 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(unique=True)),
                ('article_name', models.CharField(max_length=200)),
                ('article_wikidata', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('page_name', models.CharField(max_length=200)),
                ('page_id', models.IntegerField()),
                ('page_url', models.URLField()),
                ('referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.category')),
            ],
            options={
                'unique_together': {('referer', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.page')),
            ],
        ),
    ]
