# Generated by Django 5.1.3 on 2024-11-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_id',
        ),
    ]
