# Generated by Django 4.2.11 on 2025-02-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_page_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.page')),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.page')),
            ],
        ),
    ]
