# Generated by Django 4.2.11 on 2025-02-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_query_parser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('year', models.IntegerField(blank=True)),
                ('cctld', models.CharField(blank=True, max_length=10)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.page')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.page')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField()),
                ('images', models.IntegerField()),
                ('intrawikis', models.IntegerField()),
                ('sections', models.IntegerField()),
                ('total_edits', models.IntegerField()),
                ('first_edit', models.DateTimeField()),
                ('last_edit', models.DateTimeField()),
                ('unique_editors', models.IntegerField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.page')),
            ],
        ),
    ]
