# Generated by Django 4.2.11 on 2025-02-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_reference_authorship_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='pmid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
